apiVersion: v1
kind: ConfigMap
data:
  config: |
    #WARNING - this is being overwritten by consul-template. You can find the config at musical-spork/packer/files/config.ini.ctmpl
    [DEFAULT]
    LogLevel = DEBUG

    [DATABASE]
    Address=mariadb.service.consul
    Port=3306
    User=vaultadmin
    Password=vaultadminpassword
    Database=app

    [VAULT]
    Enabled=True
    DynamicDBCreds=True
    DynamicDBCredsPath=lob_a/workshop/database/creds/workshop-app
    Platform=kubernetes
    ProtectRecords=False
    Address=http://vault.service.consul:8200
    Token=root
    KeyPath=lob_a/workshop/transit
    KeyName=customer-key

    [CONSUL]
    DEBUG=False
metadata:
  name: config
  namespace: default