---
apiVersion: getambassador.io/v2
kind: ConsulResolver
metadata:
  name: consul-dc1
spec:
  address: consul-consul-server.default.svc.cluster.local:8500
  datacenter: dc1
---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
spec:
  type: LoadBalancer
  selector:
    service: ambassador
  ports:
  - port: 80
    targetPort: 8080
