---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-movies-app
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-movies-app-v1
  labels:
    app: go-movies-app
    version: v1
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: go-movies-app
      version: v1
  template:
    metadata: 
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-protocol: "http"
        consul.hashicorp.com/service-tags: "v1"
        consul.hashicorp.com/connect-service-upstreams: "go-movies-favorites-app:8081, vault:8200, pq-postgresql:5432"
      name: go-movies-app
      labels:
        app: go-movies-app
        version: v1
    spec:
      serviceAccountName: vault-auth
      automountServiceAccountToken: true
      containers:
        - name: go-movies-app
          image: aklaas2/go-movies-app:latest
          ports:
          - containerPort: 8080
            protocol: TCP
